version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: pck-mongo
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pck-api
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mongodb://mongo:27017
      - DB_NAME=site-visit-2
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=7d
      - JWT_COOKIE_EXPIRES_IN=7
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      - MICROSOFT_REDIRECT_URI=${MICROSOFT_REDIRECT_URI}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      # Optional storage configs
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_:qAPI_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:3001}
    container_name: pck-web
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  mongo-data:

