#!/usr/bin/env bash
set -euo pipefail

# Go to repo root (this script lives in scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR%/scripts}"
cd "$ROOT_DIR"

echo "Project root: $ROOT_DIR"

# Load .env if present (will export all vars in the file)
if [ -f .env ]; then
  echo "Loading environment variables from .env"
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

ensure_var() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"

  if [ -z "${!var_name:-}" ]; then
    if [ -n "$default_value" ]; then
      read -r -p "$prompt_text [$default_value]: " input_value || true
      input_value="${input_value:-$default_value}"
    else
      read -r -p "$prompt_text: " input_value || true
    fi
    export "$var_name"="$input_value"
  fi
}

# Ensure required env vars exist for docker-compose interpolation/build args
ensure_var "AWS_ACCESS_KEY_ID" "Enter AWS_ACCESS_KEY_ID"
ensure_var "AWS_SECRET_ACCESS_KEY" "Enter AWS_SECRET_ACCESS_KEY"
ensure_var "AWS_REGION" "Enter AWS_REGION" "ap-southeast-1"
ensure_var "AWS_S3_BUCKET" "Enter AWS_S3_BUCKET"
ensure_var "VITE_API_BASE_URL" "Enter VITE_API_BASE_URL" "http://localhost:3001"
ensure_var "MICROSOFT_CLIENT_ID" "Enter MICROSOFT_CLIENT_ID"
ensure_var "MICROSOFT_CLIENT_SECRET" "Enter MICROSOFT_CLIENT_SECRET"
ensure_var "MICROSOFT_TENANT_ID" "Enter MICROSOFT_TENANT_ID"
ensure_var "MICROSOFT_REDIRECT_URI" "Enter MICROSOFT_REDIRECT_URI"
ensure_var "SESSION_SECRET" "Enter SESSION_SECRET"
ensure_var "FRONTEND_URL" "Enter FRONTEND_URL" "http://localhost:5173"

echo "\nEnvironment summary:"
echo "  AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:0:4}********"
echo "  AWS_SECRET_ACCESS_KEY=********"
echo "  AWS_REGION=${AWS_REGION}"
echo "  AWS_S3_BUCKET=${AWS_S3_BUCKET}"
echo "  VITE_API_BASE_URL=${VITE_API_BASE_URL}"
echo "  MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}"
echo "  MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}"
echo "  MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}"
echo "  MICROSOFT_REDIRECT_URI=${MICROSOFT_REDIRECT_URI}"
echo "  SESSION_SECRET=${SESSION_SECRET}"
echo "  FRONTEND_URL=${FRONTEND_URL}"
echo

# Write .env if it does not exist so next runs are non-interactive
if [ ! -f .env ]; then
  echo "Creating .env file at project root"
  cat > .env <<EOF
# Auto-generated by scripts/compose-up.sh
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}
AWS_S3_BUCKET=${AWS_S3_BUCKET}
VITE_API_BASE_URL=${VITE_API_BASE_URL}
MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
MICROSOFT_REDIRECT_URI=${MICROSOFT_REDIRECT_URI}
SESSION_SECRET=${SESSION_SECRET}
FRONTEND_URL=${FRONTEND_URL}
EOF
fi

echo "Running: docker compose up -d --build"
docker compose up -d --build


